{{- if and .Values.clamav.certs.enabled .Values.clamav.certs.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "av-scan-service.fullname" . }}-clamav-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "av-scan-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $filename, $content := .Values.clamav.certs.files }}
  {{ $filename }}: {{ $content | b64enc }}
  {{- end }}
{{- end }}